In [1]:
#Day 2

In [2]:
#BRANCHING AND LOOPING STATEMENTS

In [3]:
#Display values from 1 to 20 using for loop
#Looping statement should end with colon
for i  in range(1,21):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [4]:
#while loop to print many times
#declare i 
i=0
while(i<10):
    print("hello welcome")
    i=i+1
    print("thank you")

hello welcome
thank you
hello welcome
thank you
hello welcome
thank you
hello welcome
thank you
hello welcome
thank you
hello welcome
thank you
hello welcome
thank you
hello welcome
thank you
hello welcome
thank you
hello welcome
thank you


In [5]:
#function definition and declaration
#keyword def is used
#function with no argument
def cse():
    print("welcome")
    return 

In [6]:
#function call
cse()

welcome


In [7]:
str="welcome"

In [8]:
str

'welcome'

In [9]:
#function with argument
def cse(str):
    print(str)
    return 

In [10]:
cse()
#for argument function pass argument

TypeError: cse() missing 1 required positional argument: 'str'

In [11]:
cse(str)

welcome


In [12]:
a=10

In [13]:
#print string 'a' number of times
def cse(str,a):
    print(str*a)
    return 

In [14]:
cse(str,a)

welcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcome


In [15]:
#NUMPY PACKAGE - Numerical Python
#including numpy package, use import statement
import numpy as np
#np is a user defined variable

In [16]:
#for creating an array in py
#int a[10] - 1D, a[10][10] - 2D, a[10][10][10] -multiD
a=np.array([1,2,3,4,5,6])

In [17]:
a

array([1, 2, 3, 4, 5, 6])

In [18]:
#ndim - to verify the dimension of array
a.ndim

1

In [19]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [20]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
b1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [22]:
b1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
b1.ndim

2

In [24]:
#create array using range function
c=np.arange(10,30)

In [26]:
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [27]:
#use step value also
d=np.arange(10,30,2)

In [28]:
d

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [29]:
#make 1D to 2D
d.shape=(2,5)

In [30]:
d

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [31]:
#printing random array using empty function
x=np.empty([3,2],dtype=int)

In [33]:
x

array([[4915277, 6225996],
       [4522070, 4325458],
       [5439567,      69]])

In [34]:
#zeros array with zeros fn
x=np.zeros(10)

In [35]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
#print one with ones fn
x=np.ones(10)

In [37]:
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
#2D array of 12 elements
t=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [39]:
t

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
#array slicing
t[0]

array([1, 2, 3])

In [41]:
t[1]

array([4, 5, 6])

In [42]:
t[1:3] #or t[1][3]

array([[4, 5, 6],
       [7, 8, 9]])

In [43]:
t[2,2] #t[2][2]

9

In [44]:
t[3,1] #t[3][1]

11